### ISSUE TITLE
Can we get rid of external css file?

### ISSUE THREAD

**Issue by jqueryisamonad** [wobsoriano/svelte-sonner#11]
Is it possible to move all styles from an external css file inside the component?

Having an external css file makes bundling a bit more complicated in cases where we want to embed all the styles in the script (embeddable widgets, custom elements, etc)

Also, `vite` doesn't work well with external css files in "library" mode https://github.com/vitejs/vite/issues/1579

**Comment by wobsoriano** [comment]
Thanks for the PR! 

Fixed in https://github.com/wobsoriano/svelte-sonner/pull/12
