### ISSUE TITLE
Setting the theme to `system` weirdly disables `richColors`

### ISSUE THREAD

**Issue by shyakadavis** [wobsoriano/svelte-sonner#19]
Hi.

Thank you so much for this port. It's been a joy using it.

Wanted to report a bug.

If you go to your `+layout.svelte` where you imported the `<Toaster />` component, and filled in the `theme` and `richColors` props like so:

```svelte
<Toaster theme="system" richColors />
```
you'll notice that the rich colors aren't applied, and you are forced to either choose between `dark` or `light` if you want to use `richColors`.

I just want to use the `system` theme as well as `richColors`.

Thanks.

**Comment by wobsoriano** [comment]
First of all, love the PP 😆 

Also, published a new version that fixes this. Feel free to reopen!

**Comment by shyakadavis** [comment]
> First of all, love the PP 😆

It's a classic. 😄 

> Also, published a new version that fixes this. Feel free to reopen!

Thank you. Will come back if I find an issue.
