### ISSUE TITLE
Is there a way to pass properties to custom components?

### ISSUE THREAD

**Issue by enyo** [wobsoriano/svelte-sonner#21]
The docs show this:

```js
import HeadlessToast from './HeadlessToast.svelte'
toast.custom(HeadlessToast)
```

But in the example provided, what if I want the time + description to be provided to the `HeadlessToast` component? Is that possible?

**Comment by enyo** [comment]
I've looked at the source and found this:

```svelte
 {#if toast.component}
    <svelte:component this={toast.component} on:closeToast={deleteToast}></svelte:component>
 {:else ...}
```

so it doesn't seem to be possible to provide data.

How about adding an additional configuration option here: https://github.com/wobsoriano/svelte-sonner/blob/6ed91735300615dfba1363fabefd86fa917055d6/src/lib/types.ts#L15-L20

I would suggest `componentProps`. This could then be applied to `<svelte:component` when instantiating.

@wobsoriano does this sound good to you? If so, I can create a PR.

**Comment by enyo** [comment]
Since I need this feature I went ahead and created a PR #22

**Comment by wobsoriano** [comment]
Hey, will take a look tomorrow. Thanks!

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/svelte-sonner/pull/22

**Comment by handlebauer** [comment]
We're seeing confusion around how to pass props to custom components. The docs site shows a "Custom with properties" example, but it's not obvious whether to use `props`, `data`, or `componentProps`. Our tests show only `props` works with `toast.custom(Component, { props, duration })`. Could the README be updated to include a minimal code sample for Svelte specifically? Thanks!
