### ISSUE TITLE
Adding multiple toasts in the same event loop breaks layout

### ISSUE THREAD

**Issue by enyo** [wobsoriano/svelte-sonner#24]
If you run this code:

```ts
toast('hello')
toast('hello')
toast('hello')
```

then the layout will be messed up when hovering:

<img width="408" alt="image" src="https://github.com/wobsoriano/svelte-sonner/assets/133277/43ba9c66-65d3-45cc-90a5-37b99980f2b8">

Creating them in a different event loop works:

```ts
toast('hello')
await new Promise((resolve) => resolve(null))
toast('hello')
await new Promise((resolve) => resolve(null))
toast('hello')
```

**Comment by wobsoriano** [comment]
Thanks for reporting! Can you try v0.3.1 and check if the issue is present there as well?

v0.3.2 introduces the ability to set position when creating a toast that might be causing this issue.

**Comment by enyo** [comment]
Downgrading to `v0.3.1` did not solve it.

**Comment by enyo** [comment]
You can see the behavior here: https://stackblitz.com/edit/sveltejs-kit-template-default-1zj9et?file=src%2Froutes%2F%2Bpage.svelte

**Comment by AyushSehrawat** [comment]
happened with me too on 0.3.3

**Comment by shimulroy842** [comment]
facing the same problem on v0.3.6

my example - [https://svelte.dev/repl/394d4436394d405c9ee5398f9dc62f1b?version=4.2.8](url)

**Comment by wobsoriano** [comment]
Any help would be much appreciated 😃

**Comment by jals1212** [comment]
This "solves" the problem (1.1.3)
```ts
await new Promise((resolve) => {
  toast('hello')
  setTimeout(resolve, 0)
})
```
