### ISSUE TITLE
Toast closes immediately

### ISSUE THREAD

**Issue by wobsoriano** [wobsoriano/svelte-sonner#31]
When the page initially loads, if you open multiple toasts consecutively, the second toast and any subsequent ones close immediately.

Here's the [original behavior](https://svelte-sonner-jkttweu55-wobsoriano.vercel.app/):

https://github.com/wobsoriano/svelte-sonner/assets/13049130/88a9d6a1-356d-4c11-bb19-ba97935c89ac

And after the internal refactor [PR](https://github.com/wobsoriano/svelte-sonner/pull/28):

https://github.com/wobsoriano/svelte-sonner/assets/13049130/d8258455-c6f2-459c-b0ab-4eaf0d027184

**Comment by huntabyte** [comment]
Will look into this! I think I have an idea as to why!

**Comment by huntabyte** [comment]
This is only happening immediately after the component mounts right? It seems afterwards it works as expected but want to confirm on your end as well!

**Comment by wobsoriano** [comment]
I just noticed now that they all close at the same time 😆 

https://github.com/wobsoriano/svelte-sonner/assets/13049130/339a62e1-6c11-4e66-994f-faa350df985a

Investigating this right now
