### ISSUE TITLE
Updating loading toast is dismissed instantly

### ISSUE THREAD

**Issue by devgauravjatt** [wobsoriano/svelte-sonner#35]
toast.loading('Loading...')

How to Stop this toast

**Comment by wobsoriano** [comment]
You will need to [update](https://github.com/wobsoriano/svelte-sonner#updating-a-toast) the toast:

```ts
const id = toast.loading('Please wait...')

setTimeout(() => {
	toast.success('Success!', { id })
}, 3000)
```

However, during testing, I also encountered this bug -  - https://github.com/emilkowalski/sonner/issues/201

**Comment by devgauravjatt** [comment]
Thanks 😊
