### ISSUE TITLE
Inconsistencies with close button toast.

### ISSUE THREAD

**Issue by ShadowThijs** [wobsoriano/svelte-sonner#36]
When playing around on the [Sonner-svelte website](https://svelte-sonner.vercel.app/) I found out that the close button is not always visible on every toast.

At the moment it seems that this happens every other toast and emilkowalski's version also seems to have some inconsistencies with the close button toast.

Below is a quick video showcasing this bug.

https://github.com/wobsoriano/svelte-sonner/assets/62294249/479511ac-6f2e-4ae7-b9e5-33bc5c2ee11f

**Comment by ShadowThijs** [comment]
This seems to be only happening on the [Sonner-svelte website](https://svelte-sonner.vercel.app/) so far.

**Comment by huntabyte** [comment]
Yeah, this is an issue with how the events are being dispatched, once you click the `Close Button` for one it sets it to all of them.

**Comment by itsEzz** [comment]
I'm experiencing the same issue in my project. When i click a toast the close button appears and when i click the top left corner the toast is dismissed even tho the button is not visible. Is there a fix planned?
