### ISSUE TITLE
[Bug] Blurry old toasts 

### ISSUE THREAD

**Issue by yb-cs** [wobsoriano/svelte-sonner#39]
![image](https://github.com/wobsoriano/svelte-sonner/assets/95703971/e6e45563-edc2-4308-a015-69a9c91dc058)
As you see in the above picture the old toasts appear to be blurry even when focusing them. The issue probably has to do with not clearing the blur effect styling of the components once we hover on them.

**Comment by wobsoriano** [comment]
Where are you getting this output? I just tried it on svelte sonner site but cant figure out how to replicate this

**Comment by pitzzahh** [comment]
It is from the documentation where you render a toast. It is also blurry from my perspective.
![image](https://github.com/wobsoriano/svelte-sonner/assets/97332554/537107fa-f7a9-4256-95c2-0f76fb856774)

**Comment by galaczi** [comment]
For me all of them are blurry. Image also from the docs page:
![image](https://github.com/wobsoriano/svelte-sonner/assets/34242243/f3daa390-26d9-4060-9cc1-bada435825cc)

**Comment by wobsoriano** [comment]
That is so weird. I am not able to replicate the issue. I'll try it on my windows machine.

**Comment by wesleyfreit** [comment]
I solved it with this:

<Toaster
      toastOptions={{
        style: { filter: 'blur(0)' },
      }}
/>

**Comment by wobsoriano** [comment]
Related https://github.com/emilkowalski/sonner/issues/334#issuecomment-1946105419
