### ISSUE TITLE
bug: Timer doesn't refresh when updating the same toast.

### ISSUE THREAD

**Issue by themixednuts** [wobsoriano/svelte-sonner#42]
When updating the same toast via toast.id, the timer doesn't refresh so toast will disappear after the original duration expires. Should reset the timer per update.

**Comment by wobsoriano** [comment]
Related to https://github.com/wobsoriano/svelte-sonner/issues/35

**Comment by huntabyte** [comment]
I'm not sure if it makes sense to reset the timer on update if a `duration` isn't passed with that update. What if my intention is to keep the toast for the same total duration, but update the appearance part of the way through? Would this still be possible?
