### ISSUE TITLE
Show timeout progress animation

### ISSUE THREAD

**Issue by aminehmida** [wobsoriano/svelte-sonner#6]
I am not sure if this is doable right now so this can be feature request:

I want to show a progress bar at the bottom of the the toast as an indicator for the user before the toast is about to close. This can be very useful especially if the toast has an action.

**Comment by wobsoriano** [comment]
Hi! I want this component to be as minimal and as close to the original [implementation](https://github.com/emilkowalski/sonner).

You can always use the `style` / `class` option to override default styling, or if you want to customize the toast even more (lose the default styling), use the [headless](https://github.com/wobsoriano/svelte-sonner#headless) option.

**Comment by aminehmida** [comment]
Got it 👍 
I am a complete noob when it comes to this. Can you direct me to where I can find a good resource?
Thanks for working on this.
