### ISSUE TITLE
richColors works in dev but not in prod

### ISSUE THREAD

**Issue by LickABrick** [wobsoriano/svelte-sonner#65]
### Describe the bug

My Toaster looks like this:

`<Toaster expand={true} richColors closeButton position="top-center" />`

When I run `npm run dev` the richColors are shown, but when I use `npm run build` followed by `npm run preview` it shows the toasts without richColors.

EDIT: it seems the close button is in richColor:
![image](https://github.com/wobsoriano/svelte-sonner/assets/17205583/9c96c3fe-054c-41d5-9736-8f845beed17d)

### Reproduction

Create Toaster component e.g. `<Toaster expand={true} richColors closeButton position="top-center" />` build app and run in preview mode.

### System Info

```bash
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Memory: 4.34 GB / 7.60 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    svelte: ^4.2.7 => 4.2.10 
    svelte-sonner: ^0.3.16 => 0.3.16
```

### Severity

annoyance

**Comment by wobsoriano** [comment]
Tried it on a fresh SK project and richColors in prod works as expected. Try to update your version!

**Comment by Scooter1337** [comment]
Same issue, using 0.3.17

**Comment by wobsoriano** [comment]
@Scooter1337  Ah, might need to update shadcn-svelte version. Would love if you can open a PR to shadcn-svelte updating sonner version!

**Comment by LickABrick** [comment]
> Same issue, using 0.3.17
> 
> @LickABrick are you using shadcn-svelte? If I switch to the vanilla Toaster, the richColors work.

Ah yes I do, completely forgot it uses it's own Toaster component.

**Comment by Scooter1337** [comment]
For some reason, in my Development build, the styles given by shadcn-svelte (they make you install 0.3.17) are overwriting the default styles.

<img width="501" alt="ss1" src="https://github.com/wobsoriano/svelte-sonner/assets/11229056/974b9a1f-8bdc-4344-a815-f59350cd2ac5">

While the exact same code (or so it seems) on shadcn-svelte's website does not. (they use 0.3.9, which I also tried, same problem on my side.) Very weird.

<img width="486" alt="ss2" src="https://github.com/wobsoriano/svelte-sonner/assets/11229056/f01b7791-70f8-4bf6-abd4-a8e3c1f97a87">

I added '!important' to all richColor styles to fix it temporarily. Any ideas? @wobsoriano

**Comment by LickABrick** [comment]
> For some reason, in my Development build, the styles given by shadcn-svelte (they make you install 0.3.17) are overwriting the default styles.
> 
> 
> 
> <img width="501" alt="ss1" src="https://github.com/wobsoriano/svelte-sonner/assets/11229056/974b9a1f-8bdc-4344-a815-f59350cd2ac5">
> 
> 
> 
> While the exact same code (or so it seems) on shadcn-svelte's website does not. (they use 0.3.9, which I also tried, same problem on my side.) Very weird.
> 
> 
> 
> <img width="486" alt="ss2" src="https://github.com/wobsoriano/svelte-sonner/assets/11229056/f01b7791-70f8-4bf6-abd4-a8e3c1f97a87">
> 
> 
> 
> I added '!important' to all richColor styles to fix it temporarily. Any ideas? @wobsoriano 
> 
> 

I think we need to move this to the Shadcn-Svelte repo as it seems to be an issue in their Toaster component.
