### ISSUE TITLE
A way to customize icon size?

### ISSUE THREAD

**Issue by wentallout** [wobsoriano/svelte-sonner#70]
I'm running into problems where my text is a little bit too big compared to the icon next to it and my icon is too small to be legible. Is there a way I can give my icons a custom size?

**Comment by wobsoriano** [comment]
You can add a class to the toast:

```ts
toast.success('Event has been created', { class: 'my-toast' })
```

or for all toasts

```svelte
<Toaster toastOptions={{ class: 'hello-world' }} />
```

then you can style the svg

```css
.my-toast [data-icon] {
	svg {
        /* style here */
	}
}
```
