### ISSUE TITLE
Please add to documentation to use svelte-portal to use toaster

### ISSUE THREAD

**Issue by goldalworming** [wobsoriano/svelte-sonner#8]
It's better to use toaster inside port
<Portal target="{document.body}" ><Toaster richColors position="top-right" /></Portal>

the toast position will relative to body not to content. at first I have to scroll to top to see toaster now it's working
and it's position can on top of modal now. please add to documentation

**Comment by Amerlander** [comment]
I add the Toaster inside the main Layout:

```js
<script>
	import '../app.scss';
	import { Toaster, toast } from 'svelte-sonner'
</script>

<div>
<Toaster richColors closeButton position="bottom-left" visibleToasts={5} />
</div>

<slot />

<style>
	div {
		position: absolute;
	}
</style>
```

and then import the toast in whatever components/pages I want to use the toasts:

```js
import { toast } from 'svelte-sonner'
toast.success('Yay!')
```
