### ISSUE TITLE
Enable horizontal swipe gesture

### ISSUE THREAD

**Issue by julien-blanchon** [wobsoriano/svelte-sonner#80]
### Change Type

Addition

### Proposed Changes

Currently the swipe gesture to dismiss a toast is only vertical. It could be usefull to have the possibility to switch to horizontal for mobile usage

**Comment by wobsoriano** [comment]
Hello! This project's goal is to remain aligned with [sonner](sonner.emilkowal.ski) which doesn't have that feature. Sorry!
