### ISSUE TITLE
Rich colors don't work when deployed to Cloudflare Pages

### ISSUE THREAD

**Issue by shyakadavis** [wobsoriano/svelte-sonner#87]
### Describe the bug

Hi;

I wanted to point out that I couldn't see rich colours rendered when my project is deployed to Cloudflare Pages, only the defaults-ish, since only the icons seem to work, but the rest of the toast not so much.

---

<img width="412" alt="Screenshot 2024-04-01 at 17 58 46" src="https://github.com/wobsoriano/svelte-sonner/assets/87414827/92f16e8a-4c3f-4e3e-a706-43f59e08a2e9">

<img width="409" alt="Screenshot 2024-04-01 at 18 03 36" src="https://github.com/wobsoriano/svelte-sonner/assets/87414827/b45a716c-6081-4f58-a970-0659adca4044">

---

Strange enough, locally everything is fine.

Thanks for the consideration.

### Reproduction

I'll prepare a repo/repro if need be, but the only way to test this, if you don't me troubling you, is to please try deploying to CF pages and see for yourself.

### System Info

```bash
System:
    OS: macOS 13.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 116.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/Library/pnpm/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.3 - ~/Library/pnpm/bun
    Watchman: 2024.03.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 123.0.6312.87
    Firefox Nightly: 126.0a1
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: ^2.5.4 => 2.5.4
    svelte: ^4.2.12 => 4.2.12
    svelte-sonner: ^0.3.19 => 0.3.19
```

### Severity

annoyance

**Comment by LickABrick** [comment]
Seeing the same thing, did you find anything to fix this?

**Comment by shyakadavis** [comment]
Sorry, but no. I understand Robert is busy atm, but hopefully we'll get some input soon. 🙂

**Comment by deronek** [comment]
Had the same bug, was fixed for me after following package updates, not sure which one included the fix:
- `mode-watcher`: 0.1.2 -> 0.3.0
- `svelte-sonner`: 0.3.11 -> 0.3.22

**Comment by wobsoriano** [comment]
@deronek is your app deployed to CF pages as well?

**Comment by deronek** [comment]
> @deronek is your app deployed to CF pages as well?

correct, richColors worked correctly in local Vite dev environment, while did not work on Cloudflare Pages deploy with SSR (exactly as in OP - close button was colored, while the toast was not).

**Comment by wobsoriano** [comment]
I have never tried deploying an app to CF pages and this is probably the best time to do it haha. I'll let you guys know if I'm able to replicate and fix it asap

**Comment by shyakadavis** [comment]
Hello;

Forgot to follow-up on this:

> Had the same bug, was fixed for me after following package updates, not sure which one included the fix:
mode-watcher: 0.1.2 -> 0.3.0
svelte-sonner: 0.3.11 -> 0.3.22

Like @deronek version `0.3.22` doesn't have the bug, and it all works as expected.

Will leave this open until you can confirm @wobsoriano 🙂 

Cheers.

**Comment by shyakadavis** [comment]
@fseda could you try installing the latest version. _Should_ be working.
