### ISSUE TITLE
Support for server-side rendering toasts

### ISSUE THREAD

**Issue by Stadly** [wobsoriano/svelte-sonner#90]
### Describe the feature

I'm using [sveltekit-flash-message](https://github.com/ciscoheat/sveltekit-flash-message) to show messages generated server-side (after redirecting POST requests). It would be great to be able to combine this with svelte-sonner, which I use to show messages that are generated client-side.

I imagine we could do something like

```svelte
// src/routes/+layout.svelte
<Toaster>
  <Toast>
    This message was generated server-side.
  </Toast>
</Toaster>
```

And then the server-side rendered toast would be hydrated on page load to behave just like the client-side rendered toasts. What do you think? With this approach, the SSR toasts will be shown even without javascript enabled.

**Comment by wobsoriano** [comment]
Same as [this](https://github.com/emilkowalski/sonner/issues/409) issue on the original sonner repo. I want to keep it as close as the original implementation... and hydrating it during SSR could introduce unnecessary overhead.

Sorry but I'll not support this for now! peace
