### ISSUE TITLE
Uncaught Error: ERR_SVELTE_TOO_MANY_UPDATES

### ISSUE THREAD

**Issue by vexkiddy** [wobsoriano/svelte-sonner#92]
### Describe the bug

When using svelte-sonner my application gets into an infinite loop. I am using svelte-5, but i'm not sure this should be causing this issue.

![CleanShot 2024-04-28 at 12 58 26@2x](https://github.com/wobsoriano/svelte-sonner/assets/2254553/c22cd794-bd4a-4127-9dd0-454c5511fa48)

![CleanShot 2024-04-28 at 13 01 26@2x](https://github.com/wobsoriano/svelte-sonner/assets/2254553/c36df373-144f-48d8-b8e0-f8584c4c3fbb)

### Reproduction

Currently i'm literally just calling this. If I remove this line I don't get the above error in the console at all.

`toast.success('Your password has been updated!');`

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 145.94 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 124.1.65.114
    Chrome: 124.0.6367.92
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: 2.5.5 => 2.5.5 
    svelte: ^5.0.0-next.55 => 5.0.0-next.55 
    svelte-sonner: ^0.3.22 => 0.3.22
```

### Severity

blocking an upgrade

**Comment by wobsoriano** [comment]
Related to https://github.com/wobsoriano/svelte-sonner/issues/38
